name: API CD 

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run:  | 
        echo " Building the Docker Image "
        docker build -t geofegeo/my_web_api .
        echo "Docker Build Complete" 
